/********************************************************************************
** Form generated from reading UI file 'juego.ui'
**
** Created by: Qt User Interface Compiler version 5.5.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_JUEGO_H
#define UI_JUEGO_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_Juego
{
public:
    QLabel *tablero;
    QFrame *dados;
    QLabel *dado1;
    QLabel *dado2;
    QPushButton *pushButton;
    QFrame *turnos;
    QLabel *iconodeturno;
    QLabel *labeldeturno;
    QFrame *banco;
    QPushButton *buyProperty;
    QLabel *monodolar;
    QFrame *cartitas;
    QLabel *banklabel;
    QLabel *monollarbank;
    QLabel *bankbalance;
    QPushButton *payJail;
    QPushButton *pushButton_2;
    QLabel *turntoPay;
    QLabel *turntoPaylbl;
    QLabel *topplayerboard;
    QFrame *p1stuff;
    QLabel *labeltopplayer;
    QLabel *icontopplayer;
    QFrame *p1money;
    QLabel *monollarsign;
    QLabel *amountp1;
    QFrame *p1properties;
    QLabel *p1p1;
    QLabel *p1p2;
    QLabel *p1p3;
    QLabel *p1p4;
    QLabel *p1p5;
    QLabel *p1p6;
    QLabel *p1p7;
    QLabel *p1p8;
    QLabel *p1p9;
    QLabel *p1p10;
    QLabel *p1p11;
    QLabel *p1p12;
    QFrame *p2stuff;
    QLabel *labelleftplayer;
    QLabel *iconleftplayer;
    QFrame *p2properties;
    QLabel *p2p1;
    QLabel *p2p2;
    QLabel *p2p3;
    QLabel *p2p4;
    QLabel *p2p5;
    QLabel *p2p6;
    QLabel *p2p7;
    QLabel *p2p8;
    QLabel *p2p9;
    QLabel *p2p10;
    QLabel *p2p11;
    QLabel *p2p12;
    QFrame *p2money;
    QLabel *amountp2;
    QLabel *monollarsign2;
    QFrame *p3stuff;
    QLabel *labelrightplayer;
    QLabel *iconrightplayer;
    QFrame *p3properties;
    QLabel *p3p1;
    QLabel *p3p2;
    QLabel *p3p3;
    QLabel *p3p4;
    QLabel *p3p5;
    QLabel *p3p6;
    QLabel *p3p7;
    QLabel *p3p8;
    QLabel *p3p9;
    QLabel *p3p10;
    QLabel *p3p11;
    QLabel *p3p12;
    QFrame *p3money;
    QLabel *monollarsign3;
    QLabel *amountp3;
    QFrame *p4stuff;
    QLabel *labelbottomplayer;
    QLabel *iconbottomplayer;
    QFrame *p3properties_2;
    QLabel *p4p1;
    QLabel *p4p2;
    QLabel *p4p3;
    QLabel *p4p4;
    QLabel *p4p5;
    QLabel *p4p6;
    QLabel *p4p7;
    QLabel *p4p8;
    QLabel *p4p9;
    QLabel *p4p10;
    QLabel *p4p11;
    QLabel *p4p12;
    QFrame *p4money;
    QLabel *monollarsign4;
    QLabel *amountp4;
    QLabel *p2onboard;
    QLabel *p3onboard;
    QLabel *p4onboard;
    QLabel *copyrights;

    void setupUi(QDialog *Juego)
    {
        if (Juego->objectName().isEmpty())
            Juego->setObjectName(QStringLiteral("Juego"));
        Juego->resize(1350, 664);
        tablero = new QLabel(Juego);
        tablero->setObjectName(QStringLiteral("tablero"));
        tablero->setGeometry(QRect(0, 0, 572, 572));
        tablero->setScaledContents(true);
        dados = new QFrame(Juego);
        dados->setObjectName(QStringLiteral("dados"));
        dados->setGeometry(QRect(580, 290, 131, 101));
        dados->setFrameShape(QFrame::StyledPanel);
        dados->setFrameShadow(QFrame::Raised);
        dado1 = new QLabel(dados);
        dado1->setObjectName(QStringLiteral("dado1"));
        dado1->setGeometry(QRect(10, 10, 51, 51));
        dado1->setScaledContents(true);
        dado2 = new QLabel(dados);
        dado2->setObjectName(QStringLiteral("dado2"));
        dado2->setGeometry(QRect(70, 10, 51, 51));
        dado2->setScaledContents(true);
        pushButton = new QPushButton(dados);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(10, 70, 111, 23));
        QFont font;
        font.setFamily(QStringLiteral("Kabel"));
        font.setBold(false);
        font.setWeight(50);
        pushButton->setFont(font);
        turnos = new QFrame(Juego);
        turnos->setObjectName(QStringLiteral("turnos"));
        turnos->setGeometry(QRect(580, 20, 131, 111));
        turnos->setFrameShape(QFrame::StyledPanel);
        turnos->setFrameShadow(QFrame::Raised);
        iconodeturno = new QLabel(turnos);
        iconodeturno->setObjectName(QStringLiteral("iconodeturno"));
        iconodeturno->setGeometry(QRect(30, 20, 71, 51));
        iconodeturno->setScaledContents(true);
        labeldeturno = new QLabel(turnos);
        labeldeturno->setObjectName(QStringLiteral("labeldeturno"));
        labeldeturno->setGeometry(QRect(10, 80, 111, 21));
        QFont font1;
        font1.setFamily(QStringLiteral("Kabel"));
        font1.setPointSize(9);
        font1.setBold(true);
        font1.setWeight(75);
        labeldeturno->setFont(font1);
        labeldeturno->setAlignment(Qt::AlignCenter);
        banco = new QFrame(Juego);
        banco->setObjectName(QStringLiteral("banco"));
        banco->setGeometry(QRect(580, 140, 131, 141));
        banco->setFrameShape(QFrame::StyledPanel);
        banco->setFrameShadow(QFrame::Raised);
        buyProperty = new QPushButton(banco);
        buyProperty->setObjectName(QStringLiteral("buyProperty"));
        buyProperty->setGeometry(QRect(10, 100, 111, 23));
        buyProperty->setFont(font);
        monodolar = new QLabel(banco);
        monodolar->setObjectName(QStringLiteral("monodolar"));
        monodolar->setGeometry(QRect(30, 10, 71, 71));
        monodolar->setScaledContents(true);
        cartitas = new QFrame(Juego);
        cartitas->setObjectName(QStringLiteral("cartitas"));
        cartitas->setGeometry(QRect(580, 400, 131, 251));
        cartitas->setFrameShape(QFrame::StyledPanel);
        cartitas->setFrameShadow(QFrame::Raised);
        banklabel = new QLabel(cartitas);
        banklabel->setObjectName(QStringLiteral("banklabel"));
        banklabel->setGeometry(QRect(10, 140, 111, 31));
        QFont font2;
        font2.setFamily(QStringLiteral("Kabel"));
        font2.setPointSize(11);
        font2.setBold(false);
        font2.setWeight(50);
        banklabel->setFont(font2);
        banklabel->setAlignment(Qt::AlignCenter);
        monollarbank = new QLabel(cartitas);
        monollarbank->setObjectName(QStringLiteral("monollarbank"));
        monollarbank->setGeometry(QRect(50, 180, 31, 31));
        monollarbank->setScaledContents(true);
        bankbalance = new QLabel(cartitas);
        bankbalance->setObjectName(QStringLiteral("bankbalance"));
        bankbalance->setGeometry(QRect(16, 220, 101, 21));
        QFont font3;
        font3.setFamily(QStringLiteral("Kabel"));
        font3.setPointSize(10);
        font3.setBold(false);
        font3.setWeight(50);
        bankbalance->setFont(font3);
        bankbalance->setAlignment(Qt::AlignCenter);
        payJail = new QPushButton(cartitas);
        payJail->setObjectName(QStringLiteral("payJail"));
        payJail->setGeometry(QRect(10, 70, 111, 23));
        payJail->setFont(font);
        pushButton_2 = new QPushButton(cartitas);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(10, 110, 111, 23));
        QFont font4;
        font4.setFamily(QStringLiteral("Kabel"));
        font4.setBold(true);
        font4.setWeight(75);
        pushButton_2->setFont(font4);
        turntoPay = new QLabel(cartitas);
        turntoPay->setObjectName(QStringLiteral("turntoPay"));
        turntoPay->setGeometry(QRect(40, 10, 47, 37));
        turntoPay->setScaledContents(true);
        turntoPaylbl = new QLabel(cartitas);
        turntoPaylbl->setObjectName(QStringLiteral("turntoPaylbl"));
        turntoPaylbl->setGeometry(QRect(10, 50, 111, 16));
        turntoPaylbl->setFont(font4);
        turntoPaylbl->setAlignment(Qt::AlignCenter);
        topplayerboard = new QLabel(Juego);
        topplayerboard->setObjectName(QStringLiteral("topplayerboard"));
        topplayerboard->setGeometry(QRect(520, 520, 41, 31));
        topplayerboard->setScaledContents(true);
        p1stuff = new QFrame(Juego);
        p1stuff->setObjectName(QStringLiteral("p1stuff"));
        p1stuff->setGeometry(QRect(720, 20, 621, 151));
        p1stuff->setFrameShape(QFrame::Box);
        p1stuff->setFrameShadow(QFrame::Raised);
        labeltopplayer = new QLabel(p1stuff);
        labeltopplayer->setObjectName(QStringLiteral("labeltopplayer"));
        labeltopplayer->setGeometry(QRect(10, 0, 201, 16));
        QFont font5;
        font5.setPointSize(12);
        labeltopplayer->setFont(font5);
        icontopplayer = new QLabel(p1stuff);
        icontopplayer->setObjectName(QStringLiteral("icontopplayer"));
        icontopplayer->setGeometry(QRect(10, 20, 41, 31));
        icontopplayer->setScaledContents(true);
        p1money = new QFrame(p1stuff);
        p1money->setObjectName(QStringLiteral("p1money"));
        p1money->setGeometry(QRect(90, 0, 521, 51));
        p1money->setFrameShape(QFrame::StyledPanel);
        p1money->setFrameShadow(QFrame::Raised);
        monollarsign = new QLabel(p1money);
        monollarsign->setObjectName(QStringLiteral("monollarsign"));
        monollarsign->setGeometry(QRect(0, 0, 31, 31));
        monollarsign->setScaledContents(true);
        monollarsign->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        amountp1 = new QLabel(p1money);
        amountp1->setObjectName(QStringLiteral("amountp1"));
        amountp1->setGeometry(QRect(10, 20, 111, 31));
        QFont font6;
        font6.setFamily(QStringLiteral("Kabel"));
        font6.setPointSize(9);
        font6.setBold(false);
        font6.setWeight(50);
        amountp1->setFont(font6);
        amountp1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        p1properties = new QFrame(p1stuff);
        p1properties->setObjectName(QStringLiteral("p1properties"));
        p1properties->setGeometry(QRect(9, 50, 601, 101));
        p1properties->setFrameShape(QFrame::StyledPanel);
        p1properties->setFrameShadow(QFrame::Raised);
        p1p1 = new QLabel(p1properties);
        p1p1->setObjectName(QStringLiteral("p1p1"));
        p1p1->setGeometry(QRect(0, 0, 91, 41));
        p1p1->setScaledContents(true);
        p1p2 = new QLabel(p1properties);
        p1p2->setObjectName(QStringLiteral("p1p2"));
        p1p2->setGeometry(QRect(0, 50, 91, 41));
        p1p2->setScaledContents(true);
        p1p3 = new QLabel(p1properties);
        p1p3->setObjectName(QStringLiteral("p1p3"));
        p1p3->setGeometry(QRect(100, 0, 91, 41));
        p1p3->setScaledContents(true);
        p1p4 = new QLabel(p1properties);
        p1p4->setObjectName(QStringLiteral("p1p4"));
        p1p4->setGeometry(QRect(100, 50, 91, 41));
        p1p4->setScaledContents(true);
        p1p5 = new QLabel(p1properties);
        p1p5->setObjectName(QStringLiteral("p1p5"));
        p1p5->setGeometry(QRect(200, 0, 91, 41));
        p1p5->setScaledContents(true);
        p1p6 = new QLabel(p1properties);
        p1p6->setObjectName(QStringLiteral("p1p6"));
        p1p6->setGeometry(QRect(200, 50, 91, 41));
        p1p6->setScaledContents(true);
        p1p7 = new QLabel(p1properties);
        p1p7->setObjectName(QStringLiteral("p1p7"));
        p1p7->setGeometry(QRect(300, 0, 91, 41));
        p1p7->setScaledContents(true);
        p1p8 = new QLabel(p1properties);
        p1p8->setObjectName(QStringLiteral("p1p8"));
        p1p8->setGeometry(QRect(300, 50, 91, 41));
        p1p8->setScaledContents(true);
        p1p9 = new QLabel(p1properties);
        p1p9->setObjectName(QStringLiteral("p1p9"));
        p1p9->setGeometry(QRect(400, 0, 91, 41));
        p1p9->setScaledContents(true);
        p1p10 = new QLabel(p1properties);
        p1p10->setObjectName(QStringLiteral("p1p10"));
        p1p10->setGeometry(QRect(400, 50, 91, 41));
        p1p10->setScaledContents(true);
        p1p11 = new QLabel(p1properties);
        p1p11->setObjectName(QStringLiteral("p1p11"));
        p1p11->setGeometry(QRect(500, 0, 91, 41));
        p1p11->setScaledContents(true);
        p1p12 = new QLabel(p1properties);
        p1p12->setObjectName(QStringLiteral("p1p12"));
        p1p12->setGeometry(QRect(500, 50, 91, 41));
        p1p12->setScaledContents(true);
        p2stuff = new QFrame(Juego);
        p2stuff->setObjectName(QStringLiteral("p2stuff"));
        p2stuff->setGeometry(QRect(720, 180, 621, 151));
        p2stuff->setFrameShape(QFrame::Box);
        p2stuff->setFrameShadow(QFrame::Raised);
        labelleftplayer = new QLabel(p2stuff);
        labelleftplayer->setObjectName(QStringLiteral("labelleftplayer"));
        labelleftplayer->setGeometry(QRect(10, 0, 201, 16));
        labelleftplayer->setFont(font5);
        iconleftplayer = new QLabel(p2stuff);
        iconleftplayer->setObjectName(QStringLiteral("iconleftplayer"));
        iconleftplayer->setGeometry(QRect(10, 20, 41, 31));
        iconleftplayer->setScaledContents(true);
        p2properties = new QFrame(p2stuff);
        p2properties->setObjectName(QStringLiteral("p2properties"));
        p2properties->setGeometry(QRect(10, 50, 601, 101));
        p2properties->setFrameShape(QFrame::StyledPanel);
        p2properties->setFrameShadow(QFrame::Raised);
        p2p1 = new QLabel(p2properties);
        p2p1->setObjectName(QStringLiteral("p2p1"));
        p2p1->setGeometry(QRect(0, 0, 91, 41));
        p2p1->setScaledContents(true);
        p2p2 = new QLabel(p2properties);
        p2p2->setObjectName(QStringLiteral("p2p2"));
        p2p2->setGeometry(QRect(0, 50, 91, 41));
        p2p2->setScaledContents(true);
        p2p3 = new QLabel(p2properties);
        p2p3->setObjectName(QStringLiteral("p2p3"));
        p2p3->setGeometry(QRect(100, 0, 91, 41));
        p2p3->setScaledContents(true);
        p2p4 = new QLabel(p2properties);
        p2p4->setObjectName(QStringLiteral("p2p4"));
        p2p4->setGeometry(QRect(100, 50, 91, 41));
        p2p4->setScaledContents(true);
        p2p5 = new QLabel(p2properties);
        p2p5->setObjectName(QStringLiteral("p2p5"));
        p2p5->setGeometry(QRect(200, 0, 91, 41));
        p2p5->setScaledContents(true);
        p2p6 = new QLabel(p2properties);
        p2p6->setObjectName(QStringLiteral("p2p6"));
        p2p6->setGeometry(QRect(200, 50, 91, 41));
        p2p6->setScaledContents(true);
        p2p7 = new QLabel(p2properties);
        p2p7->setObjectName(QStringLiteral("p2p7"));
        p2p7->setGeometry(QRect(300, 0, 91, 41));
        p2p7->setScaledContents(true);
        p2p8 = new QLabel(p2properties);
        p2p8->setObjectName(QStringLiteral("p2p8"));
        p2p8->setGeometry(QRect(300, 50, 91, 41));
        p2p8->setScaledContents(true);
        p2p9 = new QLabel(p2properties);
        p2p9->setObjectName(QStringLiteral("p2p9"));
        p2p9->setGeometry(QRect(400, 0, 91, 41));
        p2p9->setScaledContents(true);
        p2p10 = new QLabel(p2properties);
        p2p10->setObjectName(QStringLiteral("p2p10"));
        p2p10->setGeometry(QRect(400, 50, 91, 41));
        p2p10->setScaledContents(true);
        p2p11 = new QLabel(p2properties);
        p2p11->setObjectName(QStringLiteral("p2p11"));
        p2p11->setGeometry(QRect(500, 0, 91, 41));
        p2p11->setScaledContents(true);
        p2p12 = new QLabel(p2properties);
        p2p12->setObjectName(QStringLiteral("p2p12"));
        p2p12->setGeometry(QRect(500, 50, 91, 41));
        p2p12->setScaledContents(true);
        p2money = new QFrame(p2stuff);
        p2money->setObjectName(QStringLiteral("p2money"));
        p2money->setGeometry(QRect(90, 0, 521, 51));
        p2money->setFrameShape(QFrame::StyledPanel);
        p2money->setFrameShadow(QFrame::Raised);
        amountp2 = new QLabel(p2money);
        amountp2->setObjectName(QStringLiteral("amountp2"));
        amountp2->setGeometry(QRect(10, 20, 111, 31));
        amountp2->setFont(font6);
        monollarsign2 = new QLabel(p2money);
        monollarsign2->setObjectName(QStringLiteral("monollarsign2"));
        monollarsign2->setGeometry(QRect(0, 0, 31, 31));
        monollarsign2->setScaledContents(true);
        p3stuff = new QFrame(Juego);
        p3stuff->setObjectName(QStringLiteral("p3stuff"));
        p3stuff->setGeometry(QRect(720, 340, 621, 151));
        p3stuff->setFrameShape(QFrame::Box);
        p3stuff->setFrameShadow(QFrame::Raised);
        labelrightplayer = new QLabel(p3stuff);
        labelrightplayer->setObjectName(QStringLiteral("labelrightplayer"));
        labelrightplayer->setGeometry(QRect(10, 0, 201, 16));
        labelrightplayer->setFont(font5);
        iconrightplayer = new QLabel(p3stuff);
        iconrightplayer->setObjectName(QStringLiteral("iconrightplayer"));
        iconrightplayer->setGeometry(QRect(10, 20, 41, 31));
        iconrightplayer->setScaledContents(true);
        p3properties = new QFrame(p3stuff);
        p3properties->setObjectName(QStringLiteral("p3properties"));
        p3properties->setGeometry(QRect(10, 50, 601, 101));
        p3properties->setFrameShape(QFrame::StyledPanel);
        p3properties->setFrameShadow(QFrame::Raised);
        p3p1 = new QLabel(p3properties);
        p3p1->setObjectName(QStringLiteral("p3p1"));
        p3p1->setGeometry(QRect(0, 0, 91, 41));
        p3p1->setScaledContents(true);
        p3p2 = new QLabel(p3properties);
        p3p2->setObjectName(QStringLiteral("p3p2"));
        p3p2->setGeometry(QRect(0, 50, 91, 41));
        p3p2->setScaledContents(true);
        p3p3 = new QLabel(p3properties);
        p3p3->setObjectName(QStringLiteral("p3p3"));
        p3p3->setGeometry(QRect(100, 0, 91, 41));
        p3p3->setScaledContents(true);
        p3p4 = new QLabel(p3properties);
        p3p4->setObjectName(QStringLiteral("p3p4"));
        p3p4->setGeometry(QRect(100, 50, 91, 41));
        p3p4->setScaledContents(true);
        p3p5 = new QLabel(p3properties);
        p3p5->setObjectName(QStringLiteral("p3p5"));
        p3p5->setGeometry(QRect(200, 0, 91, 41));
        p3p5->setScaledContents(true);
        p3p6 = new QLabel(p3properties);
        p3p6->setObjectName(QStringLiteral("p3p6"));
        p3p6->setGeometry(QRect(200, 50, 91, 41));
        p3p6->setScaledContents(true);
        p3p7 = new QLabel(p3properties);
        p3p7->setObjectName(QStringLiteral("p3p7"));
        p3p7->setGeometry(QRect(300, 0, 91, 41));
        p3p7->setScaledContents(true);
        p3p8 = new QLabel(p3properties);
        p3p8->setObjectName(QStringLiteral("p3p8"));
        p3p8->setGeometry(QRect(300, 50, 91, 41));
        p3p8->setScaledContents(true);
        p3p9 = new QLabel(p3properties);
        p3p9->setObjectName(QStringLiteral("p3p9"));
        p3p9->setGeometry(QRect(400, 0, 91, 41));
        p3p9->setScaledContents(true);
        p3p10 = new QLabel(p3properties);
        p3p10->setObjectName(QStringLiteral("p3p10"));
        p3p10->setGeometry(QRect(400, 50, 91, 41));
        p3p10->setScaledContents(true);
        p3p11 = new QLabel(p3properties);
        p3p11->setObjectName(QStringLiteral("p3p11"));
        p3p11->setGeometry(QRect(500, 0, 91, 41));
        p3p11->setScaledContents(true);
        p3p12 = new QLabel(p3properties);
        p3p12->setObjectName(QStringLiteral("p3p12"));
        p3p12->setGeometry(QRect(500, 50, 91, 41));
        p3p12->setScaledContents(true);
        p3money = new QFrame(p3stuff);
        p3money->setObjectName(QStringLiteral("p3money"));
        p3money->setGeometry(QRect(90, 0, 521, 51));
        p3money->setFrameShape(QFrame::StyledPanel);
        p3money->setFrameShadow(QFrame::Raised);
        monollarsign3 = new QLabel(p3money);
        monollarsign3->setObjectName(QStringLiteral("monollarsign3"));
        monollarsign3->setGeometry(QRect(0, 0, 31, 31));
        monollarsign3->setScaledContents(true);
        amountp3 = new QLabel(p3money);
        amountp3->setObjectName(QStringLiteral("amountp3"));
        amountp3->setGeometry(QRect(10, 20, 111, 31));
        amountp3->setFont(font6);
        p4stuff = new QFrame(Juego);
        p4stuff->setObjectName(QStringLiteral("p4stuff"));
        p4stuff->setGeometry(QRect(720, 500, 621, 151));
        p4stuff->setFrameShape(QFrame::Box);
        p4stuff->setFrameShadow(QFrame::Raised);
        labelbottomplayer = new QLabel(p4stuff);
        labelbottomplayer->setObjectName(QStringLiteral("labelbottomplayer"));
        labelbottomplayer->setGeometry(QRect(10, 0, 201, 16));
        labelbottomplayer->setFont(font5);
        iconbottomplayer = new QLabel(p4stuff);
        iconbottomplayer->setObjectName(QStringLiteral("iconbottomplayer"));
        iconbottomplayer->setGeometry(QRect(10, 20, 41, 31));
        iconbottomplayer->setScaledContents(true);
        p3properties_2 = new QFrame(p4stuff);
        p3properties_2->setObjectName(QStringLiteral("p3properties_2"));
        p3properties_2->setGeometry(QRect(10, 50, 601, 101));
        p3properties_2->setFrameShape(QFrame::StyledPanel);
        p3properties_2->setFrameShadow(QFrame::Raised);
        p4p1 = new QLabel(p3properties_2);
        p4p1->setObjectName(QStringLiteral("p4p1"));
        p4p1->setGeometry(QRect(0, 0, 91, 41));
        p4p1->setScaledContents(true);
        p4p2 = new QLabel(p3properties_2);
        p4p2->setObjectName(QStringLiteral("p4p2"));
        p4p2->setGeometry(QRect(0, 50, 91, 41));
        p4p2->setScaledContents(true);
        p4p3 = new QLabel(p3properties_2);
        p4p3->setObjectName(QStringLiteral("p4p3"));
        p4p3->setGeometry(QRect(100, 0, 91, 41));
        p4p3->setScaledContents(true);
        p4p4 = new QLabel(p3properties_2);
        p4p4->setObjectName(QStringLiteral("p4p4"));
        p4p4->setGeometry(QRect(100, 50, 91, 41));
        p4p4->setScaledContents(true);
        p4p5 = new QLabel(p3properties_2);
        p4p5->setObjectName(QStringLiteral("p4p5"));
        p4p5->setGeometry(QRect(200, 0, 91, 41));
        p4p5->setScaledContents(true);
        p4p6 = new QLabel(p3properties_2);
        p4p6->setObjectName(QStringLiteral("p4p6"));
        p4p6->setGeometry(QRect(200, 50, 91, 41));
        p4p6->setScaledContents(true);
        p4p7 = new QLabel(p3properties_2);
        p4p7->setObjectName(QStringLiteral("p4p7"));
        p4p7->setGeometry(QRect(300, 0, 91, 41));
        p4p7->setScaledContents(true);
        p4p8 = new QLabel(p3properties_2);
        p4p8->setObjectName(QStringLiteral("p4p8"));
        p4p8->setGeometry(QRect(300, 50, 91, 41));
        p4p8->setScaledContents(true);
        p4p9 = new QLabel(p3properties_2);
        p4p9->setObjectName(QStringLiteral("p4p9"));
        p4p9->setGeometry(QRect(400, 0, 91, 41));
        p4p9->setScaledContents(true);
        p4p10 = new QLabel(p3properties_2);
        p4p10->setObjectName(QStringLiteral("p4p10"));
        p4p10->setGeometry(QRect(400, 50, 91, 41));
        p4p10->setScaledContents(true);
        p4p11 = new QLabel(p3properties_2);
        p4p11->setObjectName(QStringLiteral("p4p11"));
        p4p11->setGeometry(QRect(500, 0, 91, 41));
        p4p11->setScaledContents(true);
        p4p12 = new QLabel(p3properties_2);
        p4p12->setObjectName(QStringLiteral("p4p12"));
        p4p12->setGeometry(QRect(500, 50, 91, 41));
        p4p12->setScaledContents(true);
        p4money = new QFrame(p4stuff);
        p4money->setObjectName(QStringLiteral("p4money"));
        p4money->setGeometry(QRect(90, 0, 521, 51));
        p4money->setFrameShape(QFrame::StyledPanel);
        p4money->setFrameShadow(QFrame::Raised);
        monollarsign4 = new QLabel(p4money);
        monollarsign4->setObjectName(QStringLiteral("monollarsign4"));
        monollarsign4->setGeometry(QRect(0, 0, 31, 31));
        monollarsign4->setScaledContents(true);
        amountp4 = new QLabel(p4money);
        amountp4->setObjectName(QStringLiteral("amountp4"));
        amountp4->setGeometry(QRect(10, 20, 111, 31));
        amountp4->setFont(font6);
        p2onboard = new QLabel(Juego);
        p2onboard->setObjectName(QStringLiteral("p2onboard"));
        p2onboard->setGeometry(QRect(520, 520, 41, 31));
        p2onboard->setScaledContents(true);
        p3onboard = new QLabel(Juego);
        p3onboard->setObjectName(QStringLiteral("p3onboard"));
        p3onboard->setGeometry(QRect(520, 520, 41, 31));
        p3onboard->setScaledContents(true);
        p4onboard = new QLabel(Juego);
        p4onboard->setObjectName(QStringLiteral("p4onboard"));
        p4onboard->setGeometry(QRect(520, 520, 41, 31));
        p4onboard->setScaledContents(true);
        copyrights = new QLabel(Juego);
        copyrights->setObjectName(QStringLiteral("copyrights"));
        copyrights->setGeometry(QRect(0, 580, 572, 71));
        copyrights->setFrameShape(QFrame::NoFrame);

        retranslateUi(Juego);

        QMetaObject::connectSlotsByName(Juego);
    } // setupUi

    void retranslateUi(QDialog *Juego)
    {
        Juego->setWindowTitle(QApplication::translate("Juego", "Monopoly HND", 0));
        tablero->setText(QString());
        dado1->setText(QString());
        dado2->setText(QString());
        pushButton->setText(QApplication::translate("Juego", "Roll Dice!", 0));
        iconodeturno->setText(QString());
        labeldeturno->setText(QApplication::translate("Juego", "It's Your Turn", 0));
        buyProperty->setText(QApplication::translate("Juego", "BUY!", 0));
        monodolar->setText(QString());
        banklabel->setText(QApplication::translate("Juego", "Bank Balance", 0));
        monollarbank->setText(QString());
        bankbalance->setText(QApplication::translate("Juego", "100000", 0));
        payJail->setText(QApplication::translate("Juego", "Pay Jail Fee!", 0));
        pushButton_2->setText(QApplication::translate("Juego", "Pay Fee Later", 0));
        turntoPay->setText(QString());
        turntoPaylbl->setText(QApplication::translate("Juego", "You can...", 0));
        topplayerboard->setText(QString());
        labeltopplayer->setText(QApplication::translate("Juego", "Player 1", 0));
        icontopplayer->setText(QString());
        monollarsign->setText(QString());
        amountp1->setText(QString());
        p1p1->setText(QString());
        p1p2->setText(QString());
        p1p3->setText(QString());
        p1p4->setText(QString());
        p1p5->setText(QString());
        p1p6->setText(QString());
        p1p7->setText(QString());
        p1p8->setText(QString());
        p1p9->setText(QString());
        p1p10->setText(QString());
        p1p11->setText(QString());
        p1p12->setText(QString());
        labelleftplayer->setText(QApplication::translate("Juego", "Player 2", 0));
        iconleftplayer->setText(QString());
        p2p1->setText(QString());
        p2p2->setText(QString());
        p2p3->setText(QString());
        p2p4->setText(QString());
        p2p5->setText(QString());
        p2p6->setText(QString());
        p2p7->setText(QString());
        p2p8->setText(QString());
        p2p9->setText(QString());
        p2p10->setText(QString());
        p2p11->setText(QString());
        p2p12->setText(QString());
        amountp2->setText(QString());
        monollarsign2->setText(QString());
        labelrightplayer->setText(QApplication::translate("Juego", "Player 3", 0));
        iconrightplayer->setText(QString());
        p3p1->setText(QString());
        p3p2->setText(QString());
        p3p3->setText(QString());
        p3p4->setText(QString());
        p3p5->setText(QString());
        p3p6->setText(QString());
        p3p7->setText(QString());
        p3p8->setText(QString());
        p3p9->setText(QString());
        p3p10->setText(QString());
        p3p11->setText(QString());
        p3p12->setText(QString());
        monollarsign3->setText(QString());
        amountp3->setText(QString());
        labelbottomplayer->setText(QApplication::translate("Juego", "Player 4", 0));
        iconbottomplayer->setText(QString());
        p4p1->setText(QString());
        p4p2->setText(QString());
        p4p3->setText(QString());
        p4p4->setText(QString());
        p4p5->setText(QString());
        p4p6->setText(QString());
        p4p7->setText(QString());
        p4p8->setText(QString());
        p4p9->setText(QString());
        p4p10->setText(QString());
        p4p11->setText(QString());
        p4p12->setText(QString());
        monollarsign4->setText(QString());
        amountp4->setText(QString());
        p2onboard->setText(QString());
        p3onboard->setText(QString());
        p4onboard->setText(QString());
        copyrights->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Juego: public Ui_Juego {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_JUEGO_H
